# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
version: 2
# Set python version
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - libxkbcommon-dev
    - libpulse-dev
    - libdbus-1-dev
    - libgirepository1.0-dev
    - gir1.2-gtk-3.0
    - gir1.2-notify-0.7
    - gir1.2-gudev-1.0
    - imagemagick
    - xserver-xephyr
    - xvfb
    - dbus-x11
  jobs:
    pre_install:
      - pip install xcffib>=0.14.0 wheel
      - pip install cairocffi>=0.16.0
      - pip install -v git+https://github.com/qtile/qtile.git
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
# Optionally build your docs in additional formats such as PDF
formats:
- pdf
# Optionally set the version of Python and requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
