from . import cairo as cairo, constants as constants, ffi as ffi
from .matrix import Matrix as Matrix
from typing import Any

class FontFace:
    def __init__(self, pointer) -> None: ...

class ToyFontFace(FontFace):
    def __init__(self, family: str = ..., slant=..., weight=...) -> None: ...
    def get_family(self): ...
    def get_slant(self): ...
    def get_weight(self): ...

FONT_TYPE_TO_CLASS: Any

class ScaledFont:
    def __init__(self, font_face, font_matrix: Any | None = ..., ctm: Any | None = ..., options: Any | None = ...) -> None: ...
    def get_font_face(self): ...
    def get_font_options(self): ...
    def get_font_matrix(self): ...
    def get_ctm(self): ...
    def get_scale_matrix(self): ...
    def extents(self): ...
    def text_extents(self, text): ...
    def glyph_extents(self, glyphs): ...
    def text_to_glyphs(self, x, y, text, with_clusters): ...

class FontOptions:
    def __init__(self, **values) -> None: ...
    def copy(self): ...
    def merge(self, other) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    equal: Any
    hash: Any
    def set_antialias(self, antialias) -> None: ...
    def get_antialias(self): ...
    def set_subpixel_order(self, subpixel_order) -> None: ...
    def get_subpixel_order(self): ...
    def set_hint_style(self, hint_style) -> None: ...
    def get_hint_style(self): ...
    def set_hint_metrics(self, hint_metrics) -> None: ...
    def get_hint_metrics(self): ...
    def set_variations(self, variations) -> None: ...
    def get_variations(self): ...
