from . import cairo as cairo, ffi as ffi
from typing import Any

class Matrix:
    def __init__(self, xx: int = ..., yx: int = ..., xy: int = ..., yy: int = ..., x0: int = ..., y0: int = ...) -> None: ...
    @classmethod
    def init_rotate(cls, radians): ...
    def as_tuple(self): ...
    def copy(self): ...
    def __getitem__(self, index): ...
    def __iter__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def multiply(self, other): ...
    __mul__: Any
    def translate(self, tx, ty) -> None: ...
    def scale(self, sx, sy: Any | None = ...) -> None: ...
    def rotate(self, radians) -> None: ...
    def invert(self) -> None: ...
    def inverted(self): ...
    def transform_point(self, x, y): ...
    def transform_distance(self, dx, dy): ...
    xx: Any
    yx: Any
    xy: Any
    yy: Any
    x0: Any
    y0: Any
