from typing import Any

class ImageLoadingError(ValueError): ...

class Pixbuf:
    def __init__(self, pointer) -> None: ...
    def __getattr__(self, name): ...

def decode_to_image_surface(image_data, width: Any | None = ..., height: Any | None = ...): ...
