from units.compatibility import compatible as compatible
from units.exception import IncompatibleUnitsError as IncompatibleUnitsError
from units.quantity import Quantity as Quantity

class AbstractUnit:
    def __init__(self, is_si) -> None: ...
    def __call__(self, quantity): ...
    def canonical(self) -> None: ...
    def invert(self) -> None: ...
    def is_si(self): ...
    def squeeze(self) -> None: ...
    def str_includes_multiplier(self) -> None: ...
