from typing import Any
from units.compatibility import compatible as compatible
from units.exception import IncompatibleUnitsError as IncompatibleUnitsError

class Quantity:
    def __new__(cls, num, unit): ...
    def __init__(self, num, unit) -> None: ...
    def __getnewargs__(self): ...
    def get_num(self): ...
    num: Any
    def get_unit(self): ...
    unit: Any
    def __abs__(self): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __truediv__(self, other): ...
    __floordiv__: Any
    __div__: Any
    def __rtruediv__(self, other): ...
    __rdiv__: Any
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __cmp__(self, other): ...
    def __le__(self, other): ...
    def __complex__(self): ...
    def __float__(self): ...
    def __index__(self): ...
    def __hex__(self): ...
    def __int__(self): ...
    def __neg__(self): ...
    def __nonzero__(self): ...
    __bool__: Any
    def __oct__(self): ...
    def __pos__(self): ...
    def __pow__(self, exponent): ...

def cmp(a, b): ...
