from typing import Any
from units.registry import REGISTRY as REGISTRY

PREFIXES: Any

def prefixed(unit_str): ...
def multiplier(unit_str): ...
def without_prefix(unit_str): ...
def can_make(unit_str): ...
