from stravalib import exc as exc
from typing import Any

class ApiV3:
    server: str
    api_base: str
    log: Any
    access_token: Any
    rsession: Any
    rate_limiter: Any
    def __init__(self, access_token: Any | None = ..., requests_session: Any | None = ..., rate_limiter: Any | None = ...) -> None: ...
    def authorization_url(self, client_id, redirect_uri, approval_prompt: str = ..., scope: Any | None = ..., state: Any | None = ...): ...
    def exchange_code_for_token(self, client_id, client_secret, code): ...
    def refresh_access_token(self, client_id, client_secret, refresh_token): ...
    def get(self, url, check_for_errors: bool = ..., **kwargs): ...
    def post(self, url, files: Any | None = ..., check_for_errors: bool = ..., **kwargs): ...
    def put(self, url, check_for_errors: bool = ..., **kwargs): ...
    def delete(self, url, check_for_errors: bool = ..., **kwargs): ...
