name: ci

on:
    push:
      branches:
        - main
    pull_request:

jobs:
    build-image:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6

            - name: Build Docker image
              run: docker build -t qtile-extras-ci:local .

            - name: Save Docker image
              run: docker save qtile-extras-ci:local | gzip > qtile-extras-ci.tar.gz

            - name: Upload Docker image
              uses: actions/upload-artifact@v6
              with:
                  name: docker-image
                  path: qtile-extras-ci.tar.gz
                  retention-days: 1
    test:
        needs: build-image
        runs-on: ubuntu-24.04
        name: "python ${{ matrix.python-version }}"
        strategy:
            matrix:
                python-version: ['3.12', '3.13', '3.14']
        steps:
            - uses: actions/checkout@v4
            - name: Build Docker image
              run: |
                docker build -t qtile-extras-ci .
            - name: Run tests in container
              run: |
                mkdir coredumps
                sudo sysctl -w kernel.core_pattern=/workspace/coredumps/core-%e.%p.%t
                make ci-check
              env:
                QTILE_CI_PYTHON: ${{ matrix.python-version }}
                GITHUB_ACTIONS: true
                GITHUB_REF: ${{ github.ref }}
                GITHUB_SHA: ${{ github.sha }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                COVERALLS_FLAG_NAME: ${{ format('{0}', matrix.python-version) }}
                COVERALLS_PARALLEL: true
                COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}
            - name: Test widget decoration output
              if: ${{ matrix.python-version == '3.13' }}
              run: |
                make ci-check-decorations
            # - name: Upload generated images
            #   if: ${{ always() && matrix.python-version == '3.13' }}
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: generated-images
            #     path: decoration_images/
            #     retention-days: 5
